//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderFeedbacks = new HashSet<OrderFeedback>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int FoodItemId { get; set; }
        public int RestaurantId { get; set; }
        public string Status { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFeedback> OrderFeedbacks { get; set; }
    }
}
