//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFeedback
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Comment { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public byte Rating { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
